### ISSUE TITLE
Would you open the training code?

### ISSUE THREAD

**Issue by kings-rgb** [omriav/blended-diffusion#1]
It's a very interesting job. We want to know how to train the GAN with opened dataset. So, would you open the training code?

**Comment by omriav** [comment]
Hi,

Thank you for your interest in our project!

1. The underlying generative model is not a GAN but a diffusion model.
2. If you want to train your own custom diffusion model and then guide it using text, you can find the training code in [OpenAI's repository](https://github.com/openai/guided-diffusion) and then put the trained model in the `chekpoints` directory in our project.

Good luck!
