### ISSUE TITLE
model_output_size

### ISSUE THREAD

**Issue by fido20160817** [omriav/blended-diffusion#12]
in image_editor.py:

self.model.load_state_dict(
            torch.load(
                "checkpoints/[256x256_diffusion_uncond.pt](http://256x256_diffusion_uncond.pt/)"
                if self.args.model_output_size == 256
                else "checkpoints/[512x512_diffusion.pt](http://512x512_diffusion.pt/)",
                map_location="cpu",
            )
        )

mentioned '512x512_diffusion', is it an conditional or unconditional model? (can you share me its download link?)
It is natural that your method is built on a pretrained uncontitional model. If '512x512_diffusion' is a conditioonal model, what is the condition for face data for example? can you help me figure out this?

**Comment by omriav** [comment]
Hi,
You can download the 512x512 model from [here](https://github.com/openai/guided-diffusion).
If you download a conditional model you can feed it with the zero vector as a condition, the `image_editor.py` code can handle it.

**Comment by fido20160817** [comment]
I see, Thanks!
