### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by chenzx2** [omriav/blended-diffusion#14]
run it with cpu, and it shows a error.   RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

**Comment by omriav** [comment]
I have not tried this model on a CPU.
Some adaptations may be necessary.

**Comment by funParadox** [comment]
How can I use the GPU?

**Comment by funParadox** [comment]
Thank you. I know why. My pytorch is useless, and torch.is available() shows False. So I reinstalled a virtual environment and it worked.
