### ISSUE TITLE
what's wrong with the last row of the picture, anybody knows?

### ISSUE THREAD

**Issue by fido20160817** [omriav/blended-diffusion#15]
![img_v2_d4c761af-aa57-4528-8e69-01ef01d4c6fg](https://user-images.githubusercontent.com/21076140/209472896-fbb5b150-d8eb-40c8-b24a-7a72c08778ec.png)
 
I don't know why the subfigures in the last row are so white, any process I missed in terms of the image processing?

**Comment by omriav** [comment]
Which pre-processing method did you use?
