### ISSUE TITLE
how clip model works

### ISSUE THREAD

**Issue by davvvy** [omriav/blended-diffusion#16]
Hi! 

Thanks for your great work first.

I'm wondering how the clip model works in your code. As I learned from your code, especially image_editor.py, the input of clip model is -prompt and the output is the corresponding image. And clip is only used to compute distance(loss). However, it is supposed that clip model should take -prompt as input and then generate the corresponding image which is to be placed in the white part of the mask for final image generation. I didn't see any information about it. Maybe I missed that part. Could you please explain it?

Thanks!

**Comment by omriav** [comment]
Hi,
The CLIP model gets as an input the text prompt and produces a **text embedding**. This embedding is later being used to generate the image by the diffusion model.

**Comment by XJJVIC** [comment]
Hi!

Thanks for your reply first.

I know CLIP produces a text embedding according to line 131 of image_editor.py but I don't know how it is used to generate the image. What I know is that text embedding is used to compute loss according to line 283 of image_editor.py. Could you explain more details of how text embedding is used to generate image?


Thanks!

**Comment by davvvy** [comment]
Hi!

What I understand is:
The text embedding is used to guide the loss(final distance of line 282 in image_editor.py) between text content and the generated part in corresponding mask region in the image produced by diffusion model. The text embedding is not encoded into an image to attend diffusion model process. 

Is it right?

**Comment by omriav** [comment]
Right.
