### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by kangxi1818** [omriav/blended-diffusion#17]
thank you for your interesting work, but I have a question when runing 
python main.py -p "rock" -i "input_example/img.png" --mask "input_example/mask.png" --output_path "output"
the bug is like that
![图片](https://user-images.githubusercontent.com/117744200/224474668-37dca520-062a-4237-8841-8380d9675f49.png)
but my environment is just like you say 
![图片](https://user-images.githubusercontent.com/117744200/224474707-94e451f0-927e-4531-9c35-e5ab28ca2a51.png)

**Comment by omriav** [comment]
Hi,

Did you created the `checkpoints` directory and downloaded the pre-trained checkpoints? (step 2 in the [installation guide](https://github.com/omriav/blended-diffusion#installation))
