### ISSUE TITLE
Failure to generate correctly for very small masks

### ISSUE THREAD

**Issue by cch-meiple** [omriav/blended-diffusion#19]
Hi, thank you for your interesting work!

I wanted to generate a very small object in the image, so I input a very small mask(4-5pixels wide), but it didn't generate an object for the prompt. So I have 2 question.

1. Is there something I need to modify (e.g., parameters, pre-processing, etc..) to generate properly even with a very small mask?
2. I would be interested in your thoughts on why it fails to generate from a very small mask.

Thanks!

**Comment by omriav** [comment]
Hi,

Thank you for your interest in our work.
We actually tackled this problem of small masks in our follow-up work [Blended Latent Diffusion](https://omriavrahami.com/blended-latent-diffusion-page/).
For more details, please look for "Progressive Mask Shrinking" in this paper.

Best,
Omri
