### ISSUE TITLE
Colab

### ISSUE THREAD

**Issue by demosch** [omriav/blended-diffusion#2]
Hello! So hyped for this model. When can an Colab Version be expected? Much love

**Comment by omriav** [comment]
Thank you very much :)

I hope we will release a Colab version soon.

**Comment by demirklvc** [comment]
any updates?

**Comment by omriav** [comment]
Hi,

In recent months, we've developed an improved version of this project named [Blended Latent Diffusion](https://omriavrahami.com/blended-latent-diffusion-page/) which generates better results with a significantly faster inference time. So we will probably focus on creating an online demo of the newer project instead.

Please follow the above project to be notified when it happens.
