### ISSUE TITLE
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

### ISSUE THREAD

**Issue by cuijia1247** [omriav/blended-diffusion#21]
Thanks for your interesting work. 
I am working on the environment setup. When I installed the packages followed your instruction, 
and run the code "python main.py -p "rock" -i "input_example/img.png" --mask "input_example/mask.png" --output_path "output"

There is always one error interrupted: 
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

in 'image_editor.py' line 113:
        augmented_input = self.image_augmentations(masked_input).add(1).div(2)

This is the conda list info:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       2_gnu    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
bzip2                     1.0.8                h7f98852_4    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2023.7.22            hbcca054_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
fonttools                 4.43.1                   pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
importlib-resources       6.1.0                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
kornia                    0.6.8                    pypi_0    pypi
ld_impl_linux-64          2.40                 h41732ed_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h7f98852_5    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 13.2.0               h807b86a_2    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libgomp                   13.2.0               h807b86a_2    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libnsl                    2.0.1                hd590300_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libsqlite                 3.43.2               h2797004_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libuuid                   2.38.1               h0b41bf4_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.2.13               hd590300_5    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
lpips                     0.1.4                    pypi_0    pypi
matplotlib                3.8.0                    pypi_0    pypi
ncurses                   6.4                  hcb278e6_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
numpy                     1.26.1                   pypi_0    pypi
opencv-python             4.8.1.78                 pypi_0    pypi
openssl                   3.1.3                hd590300_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
packaging                 23.2                     pypi_0    pypi
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3               pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
pyparsing                 3.1.1                    pypi_0    pypi
python                    3.9.18          h0755675_0_cpython    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
readline                  8.2                  h8228510_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
regex                     2023.10.3                pypi_0    pypi
scipy                     1.11.3                   pypi_0    pypi
setuptools                68.2.2             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
six                       1.16.0                   pypi_0    pypi
tk                        8.6.13               h2797004_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
torch                     1.9.0+cu111              pypi_0    pypi
torchvision               0.10.0+cu111             pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
tzdata                    2023c                h71feb2d_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
wcwidth                   0.2.8                    pypi_0    pypi
wheel                     0.41.2             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
xz                        5.2.6                h166bdaf_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
zipp                      3.17.0                   pypi_0    pypi

and the cuda version info:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0

Can you help me to find out what's the problem is? THX a lot.

**Comment by omriav** [comment]
What GPU are you using?
What is the installed CUDA version on you machine?

**Comment by cuijia1247** [comment]
The GPU is Nvidia 4090, and cuda version is cuda 11.1

**Comment by midofalasol** [comment]
@cuijia1247 Hello, I also encountered the same problem. Have you resolved it?
