### ISSUE TITLE
How to train the Unet

### ISSUE THREAD

**Issue by shenwenxiao** [omriav/blended-diffusion#22]
What an amazing job! This work can help me a lot in my study.

I did not find the training code for the Unet. If I want to train the Unet for my data, how should I do?  You mention that this work is based on "[guided-diffusion](https://github.com/openai/guided-diffusion)".  Is  the Unet is trained by the code of guided-diffusion?

**Comment by omriav** [comment]
Hi,

Thank you very much.
I am recommending using [Diffusers Stable Diffusion implementation](https://github.com/omriav/blended-latent-diffusion?tab=readme-ov-file#new-fire---stable-diffusion-implementation) of our follow-up work [Blended Latent Diffusion](https://omriavrahami.com/blended-latent-diffusion-page/).

Then, you can just train your Stable Diffusion model using the [Diffusers tutorial](https://huggingface.co/docs/diffusers/training/overview) and use the trained model with the aforementioned code.

Best,
Omri
