### ISSUE TITLE
where is checkpoints (512×512)?

### ISSUE THREAD

**Issue by HuXiaoYu-shuai4** [omriav/blended-diffusion#23]
where is checkpoints (512×512)?

**Comment by omriav** [comment]
Hi,

This checkpoint is available on the [original guided-diffusion](https://github.com/openai/guided-diffusion) repository.
By the way, we recommend using the newer version of this project (which is better and faster) --- [Blended Latent Diffusion](https://omriavrahami.com/blended-latent-diffusion-page/).
