### ISSUE TITLE
Purpose of skip_timesteps

### ISSUE THREAD

**Issue by JacksonCakes** [omriav/blended-diffusion#6]
Hi, I would like to ask what is the purpose of having skip_timesteps in the code? I can't seems to find any related information on this from the paper.

**Comment by omriav** [comment]
Hi,

With this parameter you can control how much the edited area will be similar to the content in the original image.
Please see Figure 32 [in the paper](https://arxiv.org/pdf/2111.14818.pdf) - the more steps you skip, the more similar the result will be to the input.

Omri
