### ISSUE TITLE
Sounds great on paper but

### ISSUE THREAD

**Issue by Tsardoz** [omriav/blended-diffusion#9]
I tried "a person" with image2 and mask2. This is the best I got:
![08218_output_i_1_b_0](https://user-images.githubusercontent.com/10258316/174062128-c26163a7-ac35-49fb-be55-1274b2f45529.png)

**Comment by omriav** [comment]
Hi,

It was never claimed in the paper that this method will be able to generate a plausible output for **any** inputs.
In this example, adding a person to the desired place is very hard, if you use a different image that a person can
more naturally fit - you will get a better result. For example:

Input image:
![img](https://user-images.githubusercontent.com/11460440/174253199-ebf02a35-21ea-469a-bbcc-8123c7c25353.png)

Input mask:
![mask](https://user-images.githubusercontent.com/11460440/174253243-a41f7839-a0eb-4251-9b2e-513d7bc0c5bb.png)

Predictions:

![pred1](https://user-images.githubusercontent.com/11460440/174254299-fb6ff411-ae57-47c8-b32b-2e71d3448040.png)
![pred2](https://user-images.githubusercontent.com/11460440/174254307-513afa0d-ca51-4415-8976-4ebf47534805.png)

In addition, generating people is a hard task in general as you can see.
